# >>>>> INTEGRATION ENVIRONMENT VARIABLES <<<<<
spring.application.name=Veg_Ecomm_WebScraperImages
integration.env.azure.storage.account-name=vconstorage2
integration.env.azure.storage.account-key=Wzmyw9Wp5dzd4qHphKB44e2fjl58+Ojbg2lizJrqL71gUI852vc8O+M+Q2b2AyrXhkwzi9mROqZFOZWHLK5wUQ==
integration.env.azure.storage.container-name=veg-ecomm-products
integration.env.business.unit= MSB
integration.env.tvh-login-page=https://www.irmn.com/
integration.env.tvh-home-page=https://www.irmn.com/site/home.aspx

# >>>>> AZURE SQL -> VEGUSA MIDDLEWARE <- <<<<<
spring.datasource.url= jdbc:mysql://vecomdb.mysql.database.azure.com:3306/vecomdb
spring.datasource.username= vecomsqladmin
spring.datasource.password= 14}]@TT"ua882wkH6*)|>Ah^3ZN{_X8'Z)_21Zjlr;##JwN1aH
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.data.jpa.repositories.enabled= true
spring.jpa.generate-ddl= false
spring.jpa.database= default
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect