spring.application.name=ecommerce

server.port=8080

authentication=ActiveDirectoryServicePrincipal

# ERP / Synapse
spring.datasource.erp.driver-class-name=${ERP_DRIVER_CLASS}
spring.datasource.erp.jdbc-url=${ERP_JDBC_URL}
spring.datasource.erp.username=${ERP_USERNAME}
spring.datasource.erp.password=${ERP_PASSWORD}
spring.datasource.erp.hikari.maximum-pool-size=${ERP_POOL_SIZE}
spring.datasource.erp.hikari.connection-timeout=${ERP_CONNECTION_TIMEOUT}

# Nissan
spring.datasource.nissan.driver-class-name=${NISSAN_DRIVER_CLASS}
spring.datasource.nissan.jdbc-url=${NISSAN_JDBC_URL}
spring.datasource.nissan.username=${NISSAN_USERNAME}
spring.datasource.nissan.password=${NISSAN_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

sync.stock.cron-expression=${SYNC_STOCK_CRON}
sync.items.cron-expression=${SYNC_ITEMS_CRON}
sync.existencias.cron-expression=${SYNC_EXISTENCIAS_CRON}
