# >>>>> AZURE SQL -> VEGUSA MIDDLEWARE -> DB1 <<<<<
spring.veg-middleware.datasource.jdbc-url = jdbc:mysql://vecomdb.mysql.database.azure.com:3306/vecomdb
spring.veg-middleware.datasource.username = vecomsqladmin
spring.veg-middleware.datasource.password = 14}]@TT"ua882wkH6*)|>Ah^3ZN{_X8'Z)_21Zjlr;##JwN1aH
spring.veg-middleware.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.data.jpa.repositories.enabled = true
spring.jpa.generate-ddl = false
spring.jpa.database = default

# >>>>> AZURE SYNAPSE -> VEGUSA DYN365 -> DB2 <<<<<
spring.msb-data-lake.datasource.jdbc-url = jdbc:sqlserver://d365fosynapse-ondemand.sql.azuresynapse.net:1433;databaseName=DYN365PROD
spring.msb-data-lake.datasource.username = vecomsql
spring.msb-data-lake.datasource.password = YzUpZu0GCQ6qCN77PvBMfHcLKQIWVNA64HNBRYCrg8zCzAF34F
spring.msb-data-lake.datasource.driver-class-name = com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#AS IT WAS ORIGINALLY
#spring.datasource.jdbc=jdbc:mysql://localhost:3306/eirsDB
#spring.datasource.username=root
#spring.datasource.password=ivanTest
#spring.jpa.hibernate.ddl-auto=create-drop



