#spring.datasource.url=jdbc:mysql://localhost:3306/eirsDB
#spring.datasource.username=root
#spring.datasource.password=ivanTest
#spring.jpa.hibernate.ddl-auto=create-drop

#Data Lake is where the data is obtained from
spring.data-lake.datasource.url=d365fosynapse-ondemand.sql.azuresynapse.net
spring.data-lake.datasource.username=vecomsql
spring.data-lake.datasource.password=YzUpZu0GCQ6qCN77PvBMfHcLKQIWVNA64HNBRYCrg8zCzAF34F
spring.data-lake.datasource.driver-class-name=com.mysql.jdbc.Driver

#Middleware DB is where the data will be inserted
spring.middleware.datasource.jdbcUrl=jdbc:mysql://localhost:3306/booking
spring.middleware.datasource.username=vecomsqladmin
spring.middleware.datasource.password=14}]@TT"ua882wkH6*)|>Ah^3ZN{_X8'Z)_21Zjlr;##JwN1aH
spring.middleware.datasource.driver-class-name=com.mysql.jdbc.Driver