# >>>>> INTEGRATION COMPANY <<<<<
integration.company.name = MULTIVENDE

# >>>>> AZURE SQL -> VEGUSA MIDDLEWARE -> DB1 <<<<<
spring.veg-middleware.datasource.jdbc-url = jdbc:mysql://vecomdb.mysql.database.azure.com:3306/vecomdb
spring.veg-middleware.datasource.username = vecomsqladmin
spring.veg-middleware.datasource.password = 14}]@TT"ua882wkH6*)|>Ah^3ZN{_X8'Z)_21Zjlr;##JwN1aH
spring.veg-middleware.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.data.jpa.repositories.enabled = true
spring.jpa.generate-ddl = false
spring.jpa.database = default

# >>>>> AZURE SYNAPSE -> VEGUSA DYN365 -> DB2 <<<<<
spring.msb-data-lake.datasource.jdbc-url = jdbc:sqlserver://d365fosynapse-ondemand.sql.azuresynapse.net:1433;databaseName=DYN365PROD
spring.msb-data-lake.datasource.username = vecomsql
spring.msb-data-lake.datasource.password = YzUpZu0GCQ6qCN77PvBMfHcLKQIWVNA64HNBRYCrg8zCzAF34F
spring.msb-data-lake.datasource.driver-class-name = com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServerDialect

# >>>>> EXTRA CONFIGURATIONS <<<<<
# Indicates how often the token will be refreshed in milliseconds - Actually 5 hours and 45 minutes
fixedRateRefreshToken.in.milliseconds = 20700000
# Indicates the first delay to refresh token the first time the application run in milliseconds - Actually 5 hours and 45 minutes
fixedDelayRefreshToken.in.milliseconds = 20700000
fixedDelayRefreshAuthInfo.in.milliseconds = 20710000
# Indicates how often the Item Inventory will be refreshed in milliseconds - Actually 1 hour
fixedRateRefreshItemInventory.in.milliseconds = 3600000
# Indicates the first delay to refresh Item Inventory the first time the application run in milliseconds - Actually 1 minute
fixedDelayRefreshItemInventory.in.milliseconds = 30000
# Indicates how often the Price Lists will be refreshed in milliseconds - Actually 2 hours
fixedRateRefreshPriceLists.in.milliseconds = 7200000
# Indicates the first delay to refresh Price Lists the first time the application run in milliseconds - Actually 1 minute
fixedDelayRefreshPriceLists.in.milliseconds = 60000

# >>>>>>> JUMPSELLER CONFIRGURATIONS <<<<<<<<<<<<<<
jumpseller.api.base-url = https://api.jumpseller.com/v1

# >>>>>>>>> MULTIVENDE CONFIGURATIONS <<<<<<<<<<<<<<<
multivende.api.base-url = https://app.multivende.com



